export const ADDPRODUCT="ADDPRODUCT"
export const DELETEPRODUCT="DELETEPRODUCT"
export const EDITPRODUCT="EDITPRODUCT"
export const FETCHPRODUCTS="FETCHPRODUCTS"



export const ADDCAKE="ADDCAKE"
export const DELETECAKE="DELETECAKE"
export const EDITCAKE="EDITCAKE"